local path = require("awiwi.path")

describe("path.join", function()
  it("simple join, no trailing/leading slash", function() eq("a/b", path.join("a", "b")) end)
  it("trailing slash on left segment is deduped", function() eq("a/b", path.join("a/", "b")) end)
  it("leading slash on right segment is deduped", function() eq("a/b", path.join("a", "/b")) end)
  it("slash on both sides is deduped", function() eq("a/b", path.join("a/", "/b")) end)
  it("zero variadic args returns path unchanged", function() eq("a", path.join("a")) end)
  it("zero variadic args strips one trailing slash", function() eq("a", path.join("a/")) end)
  it("root alone is preserved (B-PATH-5 fix)", function() eq("/", path.join("/")) end)
  it("empty first variadic arg does not drop remaining args (B-PATH-3 fix)", function()
    eq("a/b", path.join("a", "", "b"))
  end)
  it("3+ arg left-fold join (B-PATH-2 fix, native varargs)", function()
    eq("a/b/c", path.join("a", "b", "c"))
  end)
  it("result never has a trailing slash unless it is the root", function()
    eq("a/b", path.join("a", "b/"))
  end)
end)

describe("path.absolute", function()
  it("expands ~ to home dir with no trailing slash (B-PATH-9 fix)", function()
    local home = vim.fn.expand("~")
    eq(home, path.absolute("~"))
    ok(path.absolute("~"):sub(-1) ~= "/", "must not have trailing slash")
  end)

  it("resolves a relative path against cwd", function()
    eq(vim.fs.joinpath(vim.fn.getcwd(), "relative/dir"), path.absolute("relative/dir"))
  end)
end)

describe("path.is_absolute / path.is_relative", function()
  it("absolute path", function() eq(true, path.is_absolute("/a/b")) end)
  it("relative path", function() eq(false, path.is_absolute("a/b")) end)
  it("tilde is not absolute", function() eq(false, path.is_absolute("~/a")) end)
  it("is_relative is the strict complement", function()
    for _, p in ipairs({ "/a/b", "a/b", "~/a", "", "/" }) do
      eq(not path.is_absolute(p), path.is_relative(p))
    end
  end)
end)

describe("path.split", function()
  it("absolute path gets '/' sentinel prepended", function()
    eq({ "/", "a", "b", "c" }, path.split("/a/b/c"))
  end)
  it("relative path has no sentinel", function() eq({ "a", "b" }, path.split("a/b")) end)
  it("empty path splits to empty list", function() eq({}, path.split("")) end)
  it("embedded empty component from doubled slash is preserved", function()
    eq({ "a", "", "b" }, path.split("a//b"))
  end)
  it("lone root splits to just the sentinel", function() eq({ "/" }, path.split("/")) end)
end)

describe("path.relativize", function()
  it("mismatched kind guard: absolute path, relative relative_to returns path unchanged", function()
    eq("/a/b", path.relativize("/a/b", "rel/to"))
  end)

  it("relative_to's own filename is excluded from the .. count", function()
    eq("../y/c.md", path.relativize("/a/b/y/c.md", "/a/b/x/d.md"))
  end)

  it("relative_to fully prefixes path (B-PATH-7 fix, was 'b/c')", function()
    eq("c", path.relativize("/a/b/c", "/a/b"))
  end)

  it("identical path and relative_to (B-PATH-7 fix, was 'b')", function()
    eq(".", path.relativize("/a/b", "/a/b"))
  end)
end)

describe("path.canonicalize", function()
  it("resolves .. against a preceding component", function()
    eq("/a/c", path.canonicalize("/a/b/../c"))
  end)
  it("drops '.' components", function() eq("/a/b", path.canonicalize("/a/./b")) end)
  it("clamps excess .. at the root instead of crashing (B-PATH-6 fix)", function()
    eq("/x", path.canonicalize("/../../x"))
  end)
  it("preserves leading .. for a relative path instead of crashing (B-PATH-6 fix)", function()
    eq("../../x", path.canonicalize("../../x"))
  end)
  it("root alone is preserved (B-PATH-5 fix)", function() eq("/", path.canonicalize("/")) end)
end)
