local str = require("awiwi.str")

describe("str.startswith", function()
  it("empty str, empty prefix", function() eq(true, str.startswith("", "")) end)
  it("nonempty str, empty prefix", function() eq(true, str.startswith("hello", "")) end)
  it("matching prefix", function() eq(true, str.startswith("hello", "he")) end)
  it("non-matching prefix", function() eq(false, str.startswith("hello", "lo")) end)
  it("prefix longer than str", function() eq(false, str.startswith("he", "hello")) end)
  it("empty str, nonempty prefix", function() eq(false, str.startswith("", "x")) end)
  it("prefix longer than str (exact letters)", function() eq(false, str.startswith("ab", "abc")) end)
  it("byte-safe multibyte prefix", function() eq(true, str.startswith("héllo", "h")) end)
  it("case sensitive (Bstr-2 regression guard)", function() eq(false, str.startswith("Hello", "hello")) end)
end)

describe("str.endswith", function()
  it("empty str, empty suffix", function() eq(true, str.endswith("", "")) end)
  it("nonempty str, empty suffix", function() eq(true, str.endswith("hello", "")) end)
  it("matching suffix", function() eq(true, str.endswith("hello", "lo")) end)
  it("non-matching suffix", function() eq(false, str.endswith("hello", "he")) end)
  it("suffix longer than str", function() eq(false, str.endswith("lo", "hello")) end)
  it("case sensitive (Bstr-2 regression guard)", function() eq(false, str.endswith("HELLO", "lo")) end)
end)

describe("str.contains", function()
  it("literal substring match", function() eq(true, str.contains("hello", "ell")) end)
  it("empty part in nonempty str", function() eq(true, str.contains("hello", "")) end)
  it("empty str, empty part", function() eq(true, str.contains("", "")) end)
  it("empty str, nonempty part", function() eq(false, str.contains("", "x")) end)
  it("literal match, not Lua pattern magic", function() eq(true, str.contains("a.b", "a.b")) end)
  it("does not match pattern magic char '.'", function() eq(false, str.contains("axb", "a.b")) end)
end)

describe("str.is_empty", function()
  it("empty string", function() eq(true, str.is_empty("")) end)
  it("single space", function() eq(true, str.is_empty(" ")) end)
  it("tab and newline", function() eq(true, str.is_empty("\t\n")) end)
  it("whitespace-padded text", function() eq(false, str.is_empty(" x ")) end)
  it("plain text", function() eq(false, str.is_empty("x")) end)
end)
